mv igs_tga_decode.cxx igs_tga_decode.cpp
mv igs_tga_encode.cxx igs_tga_encode.cpp
mv igs_tga_info.cxx igs_tga_info.cpp
mv igs_tga_pixel.cxx igs_tga_pixel.cpp
mv igs_tga_read_handle.cxx igs_tga_read_handle.cpp
mv igs_tga_reader.cxx igs_tga_reader.cpp
mv igs_tga_reader_plugin.cxx igs_tga_reader_plugin.cpp
mv igs_tga_writer.cxx igs_tga_writer.cpp
mv igs_tga_writer_plugin.cxx igs_tga_writer_plugin.cpp
mv tes_rw_main.cxx tes_rw_main.cpp
